Repository helm/hub, pull requests merged in 2018-12, with the labels that each got.

#9 Updating readme
  README.md
Labels: size/M

#10 Adding initial actions in process
  Repositories.md
  config/repo-values.yaml
  repos.yaml
Labels: size/M

#12 Adding contact information for stable and incubator repos
  repos.yaml
Labels: size/XS

#13 Add shortname to repositories struct
  repos.yaml
Labels: size/XS

#15 Add keel and Buildkite Helm repos
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#16 Add AppsCode charts repo to Helm hub
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#18 Add GitLab Helm chart repo to list of distributed repositories.
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#20 add bitnami chart repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#22 Add ALv2 license
  LICENSE
Labels: size/L

#23 Add Weave Flux chart repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#25 Add Jetstack helm chart repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#27 Adding IBM Cloud Private Helm Chart Repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#29 Add Kanister chart repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#30 Add Flagger Helm chart
  config/repo-values.yaml
  repos.yaml
Labels: size/XS
