Repository helm/hub, pull requests merged in 2019-05, with the labels that each got.

#71 Add emberstack repository.
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#75 Add mattermost charts repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#74 Add Funky Penguin chart repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#73 Adding k8dash
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#72 Added kafka-topics-ui chart repo ♣️
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#69 Added okgolove helm-charts repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#77 Add athens helm repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#76 Add APPUiO repo
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#78 All config names need to be lowercase for the current chart
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#83 Add Promitor Helm repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#81 Add charts.zentainer.app to repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#65 Add mmlspark spark 2.4 repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#84 Add billimek-charts repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#85 Added AppDynamics repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#86 Add Harbor repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#87 Add drgrove repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#89 addnig chart repository hmdmph to helm hub
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#88 Add kir4h repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#94 Add Lifen charts repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#95 add sstarcher repo
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#92 Add Kubernetes-based Event Driven Autoscaling (KEDA)
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#70 Automate hub deploys when merging to master
  .circleci/config.yml
  config/helm-hub-values.yaml
Labels: size/M

#96 Bumping monocular to version in use today
  .circleci/config.yml
Labels: size/XS

#97 Tweaking code commend for force CI deploy
  repos.yaml
Labels: size/XS

#98 Fixing ingress rewrite
  config/helm-hub-values.yaml
Labels: size/XS
