Repository helm/hub, pull requests merged in 2019-02, with the labels that each got.

#49 Remove trailing index.html from openfaas repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#47 Add Event Store repo
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#50 Add Ceph CSI driver repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#51 [WIP] Adding GitHub pages docs
  docs/github.md
Labels: size/M

#52 Adding ReactiveOps Stable Charts Repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS
