Repository helm/hub, pull requests merged in 2020-02, with the labels that each got.

#248 add TietoEVRY FS public repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#249 Add the Meshery Helm chart to Helm.Hub
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#252 Fix Bitnami URL
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#250 Add ClearDATA Repo
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#251 Add Blazure Repo to Listing
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#253 Add cowboysysop repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#254 Add dniel helm charts repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#255 Add Quarks charts repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#256 Helm repo for kubevirt/containerized-data-importer
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#257 Fix repos.yaml format and add check in CI
  .github/workflows/ci.yml
  repos.yaml
Labels: size/M

#258 feat: add InfluxData Charts Repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#259 Adding Dgraph charts repository
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#261 Using GitHub Actions in PRs
  .github/workflows/ci.yml
  repos.yaml
Labels: size/M

#263 Adding microcks.io/helm as new repository on Helm hub
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#265 Add Enapter repo with KeyDB multimaster setup PoC inside.
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#266 Add Eclipse Dirigible charts repository
  config/repo-values.yaml
  repos.yaml
Labels: size/S
