Repository helm/hub, pull requests merged in 2020-08, with the labels that each got.

#422 Add new Datadog Helm repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#421 Introduce Codit Helm chart repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#425 Add astarte Helm repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#429 Add stevehipwell chart repo
  config/repo-values.yaml
  repos.yaml
Labels: size/M

#432 Add fermosit helm repository.
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#426 add minio repo for the deprecated/moved minio chart
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#423 Add Neoskop charts repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#433 Add Vulcan Link helm charts
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#434 Add Vertigo Helm repository.
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#431 removing http://api.chartsm.com/ from repos.yaml : dns does not exist.
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#424 Add Kuma charts repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#436 Add percona pxc operator repository
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#435 Add descheduler repo
  config/repo-values.yaml
  repos.yaml
Labels: size/S

#437 add anchore charts to hub repos
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#441 Add kubernetes/ingress-nginx helm repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#440 Add Polyaxon's official helm charts repo
  config/repo-values.yaml
  repos.yaml
Labels: size/XS

#442 add lakefs to helm hub
  config/repo-values.yaml
  repos.yaml
Labels: size/XS
